## Assignment 1 - Pandas 

### Part 1 
The columns are organized as the number of Summer games, Summer mdeals, number of Winter games, Winter medals, total number of medals. 

### Exploring dataset to create function

In [3]:
import pandas as pd

In [2]:
pd.read_csv("olympics.csv")

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,# Summer,01 !,02 !,03 !,Total,# Winter,01 !,02 !,03 !,Total,# Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
5,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
6,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
7,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
8,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
9,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
10,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
11,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
12,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
13,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
14,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
15,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
16,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
17,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
18,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
19,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
20,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
21,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
22,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
23,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
24,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
25,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
26,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
27,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
28,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
29,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
119,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
120,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
121,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
122,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
123,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
124,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
125,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
126,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
127,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
128,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
129,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
130,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
131,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
132,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
133,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
134,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
135,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
136,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
137,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
138,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
139,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
140,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
141,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
142,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [4]:
pd.read_csv('olympics.csv',index_col=0)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,,,,,,,,,,,,,,,
NaN,# Summer,01 !,02 !,03 !,Total,# Winter,01 !,02 !,03 !,Total,# Games,01 !,02 !,03 !,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [7]:
pd.read_csv('olympics.csv',index_col=0,skiprows=1)

,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [33]:
pd.read_csv('olympics.csv',skiprows=1)

,Unnamed: 0,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
5,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
6,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
7,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
8,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
9,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
10,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
11,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
12,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
13,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
14,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
15,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
16,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
17,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
18,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
19,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
20,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
21,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
22,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
23,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
24,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
25,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
26,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
27,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
28,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
29,Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
118,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
119,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
120,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
121,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
122,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
123,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
124,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
125,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
126,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
127,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
128,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
129,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
130,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
131,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
132,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
133,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
134,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
135,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
136,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
137,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
138,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
139,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
140,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
141,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
142,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
143,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
144,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
145,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
146,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [64]:
df = pd.read_csv('olympics.csv',skiprows=1)
first_row = df.iloc[0,0]
first_row

'Afghanistan\xc2\xa0(AFG)'

In [41]:
df.head()

,Unnamed: 0,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [42]:
first_row.split('\xc2\xa0')

['Afghanistan', '(AFG)']

In [43]:
first_row.split('\xc2\xa0')[0]

'Afghanistan'

In [44]:
df['Unnamed: 0'] = df['Unnamed: 0'].apply(lambda x: x.split('\xc2\xa0')[0])
df.head(5)

,Unnamed: 0,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [48]:
#How do I set the first column as the index? 
df.set_index(df['Unnamed: 0'].values,inplace=True)
df.head()

,Unnamed: 0,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan,Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria,Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina,Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia,Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia,Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [59]:
del df['Unnamed: 0']

In [52]:
df.head()

,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [63]:
df.head()

,# Summer,01 !,02 !,03 !,Total,# Winter,01 !.1,02 !.1,03 !.1,Total.1,# Games,01 !.2,02 !.2,03 !.2,Combined total
0,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [61]:
def load_data(csv_file):
    """
    Create a dataframe with following data cleanup to make this file
    readble.
        - Create a function load_data to read CSV file and convert 
        CSV data to dataframe.
        - Skip first row
        - Rename column containing 01, 02 and 03 to Gold, Silver 
        and Bronze
        - Split country name and country code and add country name 
        as data frame index
        - Remove extra unnecessary characters from country name.
        - Drop the column Totals
        - Return dataframe.
    """
    
    df = pd.read_csv(csv_file,index_col=0,skiprows=1)
    renamed_col = {'01 !': 'Gold',
                    '02 !': 'Silver',
                    '03 !': 'Bronze',
                    '01 !.1': 'Gold',
                    '02 !.1': 'Silver',
                    '03 !.1': 'Bronze',
                    '01 !.2': 'Gold',
                    '02 !.2': 'Silver',
                    '03 !.2': 'Bronze',
                   'Total.1': 'Total'}
    
    #Renaming the columns
    df.rename(columns = renamed_col,inplace=True)
    
    #Renaming column 0 to make it more neater
    df.iloc[:,0] = df.iloc[:,0].apply(lambda x:x.split('\xc2\xa0')[0])
    
    #Setting first column as the index
    df.set_index(df['Unnamed: 0'].values,inplace=True)
    
    #Dropping the first column since it has now been set by the index
    del df['Unnamed: 0']
    
    #Removing totals column
    del df['Total']
    
    return df

### Getting First Country Details from Dataframe 
Using the above function to get first country details by:
- Creating a function to return results for first country.

In [62]:
load_data('olympics.csv')

AttributeError: 'int' object has no attribute 'split'